apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-worker-scaler
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: notification-worker
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 8
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: notifications
        mode: QueueLength
        value: "5"
        activationValue: "1"
      authenticationRef:
        name: rabbitmq-trigger-auth
