apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: keda-demo
type: Opaque
stringData:
  host: "amqp://guest:guest@rabbitmq.keda-demo.svc:5672"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: keda-demo
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-credentials
      key: host
