apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: keda-demo
  labels:
    app: notification-worker
    app.kubernetes.io/part-of: demo-3-rabbitmq
    app.openshift.io/runtime: nodejs
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"rabbitmq"}]'
spec:
  replicas: 0
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: notification-worker
          image: image-registry.openshift-image-registry.svc:5000/keda-demo/notification-worker:latest
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: QUEUE_NAME
              value: notifications
            - name: PROCESSING_TIME_MS
              value: "2000"
            - name: PREFETCH
              value: "3"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
